name: Discord Notification

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send NovaCo Push Notification
        run: |
          COMMIT_MSG="${{ github.event.head_commit.message }}"
          COMMIT_URL="${{ github.event.head_commit.url }}"
          REPO_URL="https://github.com/${{ github.repository }}"
          
          if [ -z "$COMMIT_MSG" ]; then COMMIT_MSG="Manual commit test."; fi
          if [ -z "$COMMIT_URL" ]; then COMMIT_URL="$REPO_URL"; fi

          curl -i -H "Content-Type: application/json" \
               -X POST \
               -d '{
            "content": "<@&1490287716192223332>",
            "embeds": [
              {
                "title": NovaCo Update",
                "color": 3327231,
                "thumbnail": {
                  "url": "https://avatars.githubusercontent.com/u/272980283?s=200&v=4"
                },
                "fields": [
                  {
                    "name": "📂 Repository",
                    "value": "`${{ github.repository }}`",
                    "inline": true
                  },
                  {
                    "name": "🆔 Build",
                    "value": "`v1.0.${{ github.run_number }}`",
                    "inline": true
                  },
                  {
                    "name": "📝 Change Log",
                    "value": "```fix\n'"$COMMIT_MSG"'\n```",
                    "inline": false
                  }
                ],
                "footer": {
                  "text": "NovaCo",
                },
                "timestamp": "'$(date -u +%Y-%m-%dT%H:%M:%SZ)'"
              }
            ],
            "components": [
              {
                "type": 1,
                "components": [
                  {
                    "type": 2,
                    "style": 5,
                    "label": "Review Changes",
                    "url": "'"$COMMIT_URL"'",
                    "emoji": { "name": "✨" }
                  },
                  {
                    "type": 2,
                    "style": 5,
                    "label": "Source",
                    "url": "https://github.com/${{ github.repository }}",
                    "emoji": { "name": "🐙" }
                  }
                ]
              }
            ]
          }' "${{ secrets.DISCORD_WEBHOOK_URL }}"